### PR TITLE
1.90 update

### PR DESCRIPTION
**Pull request by TheGoldyOne**

### CODE REVIEW

**Comment by zloxen** [comment]
Yay! I've been missing this thing thanks man 👍👍👍👍

**Comment by zloxen** [comment]
Do you want hacktoberfest-accepted label?

**Comment by TheGoldyOne** [comment]
yeah sure!

**Comment by zloxen** [comment]
can you check out my other repo: https://github.com/zloxen/RevolutionRoleplay and fix the bug with car shop for civilians?

**Comment by TheGoldyOne** [comment]
lemme see it

**Pull request merged**
